### ISSUE TITLE
how to use send message to channels

### ISSUE THREAD

**Issue by tuan-zigvy** [necordjs/necord#914]
### What is your question?

`
@Injectable()
export class GeneralLogger implements LoggerService {
  private readonly logger = new Logger(GeneralLogger.name);

  public constructor(
    private readonly client: Client,
    private readonly configServer: ConfigService,
  ) {}

  @Once('ready')
  public onReady(@Context() [client]: ContextOf<'ready'>) {
    this.logger.log(`Bot logged in as ${client.user.username}`);
  }

  @On('warn')
  public onWarn(@Context() [message]: ContextOf<'warn'>) {
    this.logger.warn(message);
  }

  log(message: string): void {
    this.logger.log('info', message);
  }

  error(message: string): void {
    this.logger.log('error', message);
  }

  warn(message: string): void {
    this.logger.log('warn', message);
  }

  debug(message: string): void {
    this.logger.log('debug', message);
  }

  verbose(message: string): void {
    this.logger.log('debug', message);
  }

  sendToMessage(message: string) {
    const channel = this.client.channels.cache.get('1131273538611982538') as any;
    channel.send(message);
  }
}
`
necord  version 6.1

error 'TypeError: undefined is not an object (evaluating 'this.client.channels.cache.get("1131273538611982538").send')
    at sendToMessage (/home/tuan-dd/repos/project_mentor/src/global/services/logger-general.service.ts:49:24)
    at getHello (/home/tuan-dd/repos/project_mentor/src/app.service.ts:9:11)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/router/router-execution-context.js:37:48)
    at intercept (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:10:16)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/router/router-execution-context.js:46:51)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/router/router-execution-context.js:40:30)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/router/router-proxy.js:10:12)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/@nestjs/core/router/router-proxy.js:7:16)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/route.js:146:11)
    at dispatch (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/route.js:115:21)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:283:43)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at <anonymous> (node:domain:34:22)
    at runInContextMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/request-context/lib/index.js:136:28)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/home/tuan-dd/repos/project_mentor/node_modules/body-parser/lib/types/urlencoded.js:91:6)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/home/tuan-dd/repos/project_mentor/node_modules/body-parser/lib/types/json.js:113:6)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:518:6)
    at xXssProtectionMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:294:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xPoweredByMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:287:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xPermittedCrossDomainPoliciesMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:280:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xFrameOptionsMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:264:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xDownloadOptionsMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:244:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xDnsPrefetchControlMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:237:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at xContentTypeOptionsMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:229:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at strictTransportSecurityMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:222:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at referrerPolicyMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:190:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at originAgentClusterMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:165:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at crossOriginResourcePolicyMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:158:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at crossOriginOpenerPolicyMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:142:7)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at contentSecurityPolicyMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:107:8)
    at internalNext (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:514:46)
    at helmetMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/helmet/index.mjs:518:6)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at compression (/home/tuan-dd/repos/project_mentor/node_modules/compression/index.js:219:9)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at logger (/home/tuan-dd/repos/project_mentor/node_modules/morgan/index.js:143:9)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at cors (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:187:11)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:225:13)
    at originCallback (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:213:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:219:27)
    at optionsCallback (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:198:18)
    at corsMiddleware (/home/tuan-dd/repos/project_mentor/node_modules/cors/lib/index.js:204:12)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/middleware/init.js:39:9)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
    at process_params (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:349:6)
    at next (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:280:10)
    at query (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/middleware/query.js:44:9)
    at handle (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/layer.js:94:21)
    at trim_prefix (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:327:41)
    at <anonymous> (/home/tuan-dd/repos/project_mentor/node_modules/express/lib/router/index.js:288:13)
localhost - - [25/Sep/2023:18:11:01 +0000] "GET / HTTP/1.1" - - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"'

**Comment by SocketSomeone** [comment]
Looks like channel cannot get from the cache use `fetch` method and typeguard isTextBased()

**Comment by SocketSomeone** [comment]
Also, what intents do you use?

**Comment by tuan-zigvy** [comment]
i use  intents: ['Guilds', 'GuildMessages', 'DirectMessages', 'MessageContent']

**Comment by tuan-zigvy** [comment]
> Looks like channel cannot get from the cache use `fetch` method and typeguard isTextBased()

i want when have error , server send message to discord  like logger

**Comment by SocketSomeone** [comment]
Checkout is you client injected? Looks like your client is undefined
